# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: TRHX'S BLOG
# logo: images/logo.png
subtitle: 一入 IT 深似海 从此学习无绝期
description: TRHX 的个人博客；主攻 Python、爬虫、WEB前端、大数据、数据分析、数据可视化；求知若饥，虚心若愚，一入 IT 深似海，从此学习无绝期，记录毕生所学！
keywords: Python爬虫,数据分析,数据可视化,web前端,Java,Python,HTML,软件工程,大学生,hexo,GitHubPages,CodingPages
author: TRHX
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.itrhx.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material-x-1.2.1

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repository:
    github: git@github.com:TRHX/TRHX.github.io.git
    coding: git@git.dev.tencent.com:TRHX/TRHX.git
  branch: master
- type: baidu_url_submitter

# 博客备份
backup:
  type: git
  theme: material-x-1.2.1
  message: Back up my www.itrhx.com blog
  repository:
    github: git@github.com:TRHX/TRHX.github.io.git,backup
    coding: git@git.dev.tencent.com:TRHX/TRHX.git,backup

# 提交百度搜索
baidu_url_submit:
  count: 200
  host: www.itrhx.com
  token: igTjk1xBNcyfKrDX
  path: baidu_urls.txt

# 端口号
server:
  port: 5000
  compress: true
  header: true

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

live2d:
  enable: false
  scriptFrom: local
  model:
    use: live2d-widget-model-haruto
  display:
    position: right
    width: 100
    height: 200
  mobile:
    show: false

#RSS订阅
plugin:
  - hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20

# 网页标签图标
favicon: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.3/images/favicon.ico
# 作者头像
avatar: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.3/images/trhx.png

# 全局导入
import:
  meta:
  - "<meta name='theme-color' content='#f24e32'>"
  - "<meta name='msapplication-TileColor' content='#f24e32'>"
  - "<meta name='msapplication-config' content='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/browserconfig.xml'>"
  link:
  - "<link rel='shortcut icon' type='image/x-icon' href='https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.3/images/favicon.ico'>"
  - "<link rel='icon' type='image/x-icon' sizes='32x32' href='https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.3/images/favicon-32x32.png'>"
  - "<link rel='apple-touch-icon' type='image/png' sizes='180x180' href='https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.3/images/apple-touch-icon.png'>"
  - "<link rel='mask-icon' color='#f24e32' href='https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.3/images/safari-pinned-tab.svg'>"
  - "<link rel='manifest' href='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-favicon@19.9.7/site.webmanifest'>"

baidu_analytics_key: df0bc7c6bdbd80356ba4db429724ccad

gitalk:
  enable: true
  clientID: d19a84b9d9a2ddb2c6b9
  clientSecret: cec9feae5129a6106edc68ce06d167be8eb06021
  repo: trhx.github.io
  owner: TRHX
  admin: [TRHX]
