############################### 基本信息 ###############################
info:
  name: Material X
  docs: https://xaoxuu.com/wiki/material-x/
  cdn: # 把对应的那一行注释掉就使用本地的文件
    css:
      style: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/css/style.css
    js:
      app: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/app.js
      search: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/search.js
      volantis: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/volantis.min.js



############################### 主题风格 ###############################
# style: material    # material: 导航栏和标题栏背景是主题色
style: pure        # pure: 导航栏和标题栏背景是白色


############################### 服务开关 ###############################
scrollreveal: true
nodewaves: true
busuanzi: true
# fastclick: true



############################### 默认值 ###############################
# 音乐控件的默认配置，如果sidebar或者page里没有提供，就取这里的参数
music:
  enable: true      # 是否启用
  color: '#1BCDFC'  # 主题色
  mode: circulation # random （随机） single （单曲） circulation （列表循环） order （列表）
  server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
  type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
  id: 3019271605    # 歌曲/专辑/歌单 ID
  volume: 0.7       # 音量, 0~1
  autoplay: false   # 自动播放

# 友链页头像占位图
avatar_placeholder: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/bitmap.gif

# 文章字数统计、阅读时长
word_count: true

# Reward
reward:
  enable: true
  reward_comment: 您的喜欢是作者写作最大的动力！❤️
  PayPalLink: https://paypal.me/trhx
  AliPayOR: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/reward/AliPayQR.png
  WeChatPayOR: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/reward/WeChatQR.png
  QQPayOR: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/reward/QQPayQR.png

# 日期格式 http://momentjs.com/docs/
date_format: 'YYYY-MM-DD' # 文章发布日期的格式
updated_date_format: 'll' # 文章更新日期的格式

# 幻灯片
backstretch:
  position: cover  # cover: 封面背景   full: 整个网页背景
  duration: 5000 # 持续时间（毫秒）
  fade: 1500     # 渐变（毫秒）
  images:
    #- https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/background/023.webp
    #- https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/background/022.webp
    #- https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/background/021.webp


############################### 自定义 ###############################
# page的封面
cover:
  scheme: search    # 后期将会提供多种封面方案
  height: full      # full（默认值）: 首页封面占据整个第一屏幕，其他页面占半个屏幕高度， half: 所有页面都封面都只占半个屏幕高度
  # title: "TRHX'S BLOG"
  logo: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/logo.png    # logo和title只显示一个，若同时设置，则只显示logo
  search_placeholder: '世界之大，探索一下！'
  # 主页封面菜单
  features:
    - name: 主页
      icon: fas fa-home
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 朋友
      icon: fas fa-users
      url: friends/
    - name: 留言
      icon: fas fa-comments
      url: comments/

# 桌面端导航栏菜单
menu_desktop:
  - name: 主页
    icon: fas fa-home
    url: /
  - name: 归档
    icon: fas fa-archive
    url: archives/
  - name: 朋友
    icon: fas fa-users
    url: friends/
  - name: 留言
    icon: fas fa-comments
    url: comments/
  - name: 关于
    icon: fas fa-info-circle
    url: about/
    target: _blank
  - name: 百宝箱
    icon: fas fa-tools
    url: box/
    target: _blank
  - name: 米店
    icon: fas fa-link
    url: https://mi.aliyun.com/shop/40012
    target: _blank
  - name: 肺炎疫情图
    icon: fas fa-heart
    url: 2019-nCoV/
    target: _blank

# 手机端导航菜单（从右上角的按钮点击展开）
menu_mobile:
  - name: 主页
    icon: fas fa-home
    url: /
  - name: 归档
    icon: fas fa-archive
    url: archives/
  - name: 朋友
    icon: fas fa-users
    url: friends/
  - name: 留言
    icon: fas fa-comments
    url: comments/
  - name: 米店
    icon: fas fa-link
    url: https://mi.aliyun.com/shop/40012
  - name: 百宝箱
    icon: fas fa-tools
    url: box/
  - name: CSDN
    icon: fab fa-cuttlefish
    url: https://itrhx.blog.csdn.net/
  - name: 肺炎疫情图
    icon: fas fa-heart
    url: 2019-nCoV/

# 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
# 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
# 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
meta:
  header: [title, author, date, categories, counter, wordcount, top]
  footer: [updated, tags, share]

# 主体元素，你也可以在页面的Front-matter中设置
body: [article, comments]

# 侧边栏小部件，默认按下面给定的顺序全部显示，文章中还可以自定义显示一部分以及顺序
sidebar:
  - widget: author
    avatar: https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/trhx.png
    title: ๑۩ﺴ&nbsp;&nbsp;TRHX&nbsp;&nbsp;ﺴ۩๑
    #body: Stay Hungry, Stay Foolish!
    social: true
  - widget: toc
  - widget: grid
    icon: fas fa-map-signs
    title: 站内导航
    rows:
      - name: 所有文章
        icon: fas fa-clock
        url: /
      - name: 文章归档
        icon: fas fa-archive
        url: archives/
      - name: RSS订阅
        icon: fas fa-rss
        url: /atom.xml
      - name: 我的友链
        icon: fas fa-link
        url: friends/
      - name: 留言板
        icon: fas fa-comments
        url: comments/
        target: _blank
      - name: 关于博主
        icon: fas fa-info-circle
        url: about/
        rel: nofollow
  - widget: plain
    icon: fas fa-handshake
    title: 欢迎光临
    body: '<script src="https://pv.sohu.com/cityjson?ie=utf-8"></script><script>var getOSAndBrowser=function(){var os=navigator.platform;var userAgent=navigator.userAgent;var info="";var tempArray="";if(os.indexOf("Win")>-1){if(userAgent.indexOf("Windows NT 5.0")>-1){info+="Win2000"}else if(userAgent.indexOf("Windows NT 5.1")>-1){info+="WinXP"}else if(userAgent.indexOf("Windows NT 5.2")>-1){info+="Win2003"}else if(userAgent.indexOf("Windows NT 6.0")>-1){info+="WindowsVista"}else if(userAgent.indexOf("Windows NT 6.1")>-1||userAgent.indexOf("Windows 7")>-1){info+="Win7"}else if(userAgent.indexOf("Windows NT 6.2")>-1||userAgent.indexOf("Windows 8")>-1){info+="Win8"}else if(userAgent.indexOf("Windows NT 6.3")>-1||userAgent.indexOf("Windows 8.1")>-1){info+="Win8.1"}else if(userAgent.indexOf("Windows NT 10.0")>-1||userAgent.indexOf("Windows 10")>-1){info+="Win10"}else{info+="Other"}}else if(os.indexOf("Mac")>-1){info+="Mac"}else if(os.indexOf("X11")>-1){info+="Unix"}else if(os.indexOf("Linux")>-1){info+="Linux"}else{info+="Other"}info+="/";var isOpera=userAgent.indexOf("Opera")>-1;var isIE=userAgent.indexOf("compatible")>-1&&userAgent.indexOf("MSIE")>-1&&!isOpera;var isEdge=userAgent.toLowerCase().indexOf("edge")>-1&&!isIE;var isIE11=(userAgent.toLowerCase().indexOf("trident")>-1&&userAgent.indexOf("rv")>-1);if(/[Ff]irefox(\/\d+\.\d+)/.test(userAgent)){tempArray=/([Ff]irefox)\/(\d+\.\d+)/.exec(userAgent);info+=tempArray[1]+tempArray[2]}else if(isIE){var version="";var reIE=new RegExp("MSIE (\\d+\\.\\d+);");reIE.test(userAgent);var fIEVersion=parseFloat(RegExp["$1"]);if(fIEVersion==7){version="IE7"}else if(fIEVersion==8){version="IE8"}else if(fIEVersion==9){version="IE9"}else if(fIEVersion==10){version="IE10"}else{version="0"}info+=version}else if(isEdge){info+="Edge"}else if(isIE11){info+="IE11"}else if(/[Cc]hrome\/\d+/.test(userAgent)){tempArray=/([Cc]hrome)\/(\d+)/.exec(userAgent);info+=tempArray[1]+tempArray[2]}else if(/[Vv]ersion\/\d+\.\d+\.\d+(\.\d)* *[Ss]afari/.test(userAgent)){tempArray=/[Vv]ersion\/(\d+\.\d+\.\d+)(\.\d)* *([Ss]afari)/.exec(userAgent);info+=tempArray[3]+tempArray[1]}else if(/[Oo]pera.+[Vv]ersion\/\d+\.\d+/.test(userAgent)){tempArray=/([Oo]pera).+[Vv]ersion\/(\d+)\.\d+/.exec(userAgent);info+=tempArray[1]+tempArray[2]}else{info+="unknown"}return info};document.write("欢迎来自"+returnCitySN["cname"]+"的朋友");document.write("<br>您的 IP 是："+returnCitySN["cip"]);document.write("<br>您使用的是："+getOSAndBrowser());</script>'
  - widget: plain
    icon: fas fa-map-marked-alt
    title: 访客地图
    body: '<div style="position: relative;"><script type="text/javascript" src="//rf.revolvermaps.com/0/0/4.js?i=5eyl60h41k1&amp;m=6&amp;h=122&amp;c=ff0000&amp;r=30" async="async"></script></div>'
    more:
      icon: fas fa-info-circle
      url: https://www.revolvermaps.com/
      target: _blank
  - widget: plain
    icon: fas fa-comments
    title: 交流群组
    body: '<img src="https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/images/groups.png"><a id="goroups_button" class="goroups_button_new" target="_blank" href="https://jq.qq.com/?_wv=1027&k=5F6HRuG">QQ 交流群</a><a id="goroups_button" class="goroups_button_new" target="_blank" href="https://t.me/joinchat/Mro2h0uVt0DpDvOofWG65A">Telegram 交流群</a>'
#  - widget: list
#    icon: fas fa-link
#    title: 特别链接
#    rows:
#      - name: bilibili
#        desc: 博主的主页
#        icon: fas fa-film
#        url: http://space.bilibili.com/314463806?/
#      - name: Material X
#        desc: Hexo博客主题
#        icon: fas fa-cube
#        url: https://xaoxuu.com/wiki/material-x/
#      - name: Hexo
#        desc: Hexo官网
#        icon: fas fa-blog
#        url: https://hexo.io/zh-cn/
  - widget: category
    more:
      icon: fas fa-expand-arrows-alt
      url: categories/
      rel: nofollow
  - widget: tagcloud
    icon: fas fa-fire
    more:
      icon: fas fa-expand-arrows-alt
      url: tags/
      rel: nofollow
  # - widget: related_posts # 需要安装插件  npm i -S hexo-related-popular-posts
  - widget: music
    icon: fas fa-compact-disc
    title: "最近在听"
    more:
      icon: far fa-heart
      url: https://music.163.com/#/user/home?id=3019271605
      rel: external nofollow noopener noreferrer
      target: _blank
    server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
    type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
    id: 3019271605     # 歌曲/专辑/歌单 ID

# 社交信息
social:
  - icon: fab fa-github
    url: https://github.com/TRHX
  - icon: fab fa-cuttlefish
    url: https://itrhx.blog.csdn.net/
  - icon: fab fa-zhihu
    url: https://www.zhihu.com/people/tan-70-56/activities
  - icon: fas fa-envelope
    url: mailto:admin@itrhx.com
  #- icon: fas fa-envelope
  #  url: http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=-4uNl4e-mZCHkp6Wk9GckJI
  - icon: fab fa-qq
    url: http://wpa.qq.com/msgrd?v=3&uin=2273902448&site=qq&menu=yes


# 分享按钮
# 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
share:
  - id: qq
    name: QQ好友
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
  - id: qzone
    name: QQ空间
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
  - id: qrcode
    name: 微信
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
  - id: weibo
    name: 微博
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
  - id: qrcode
    name: QRcode
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png


# footer: '页脚文字，支持[markdown](/)'


############################### 评论系统 ###############################
# disqus_shortname: 要使用哪个请复制到根目录配置文件！
# livere_uid: 要使用哪个请复制到根目录配置文件！
# gitalk: 要使用哪个请复制到根目录配置文件！
#   clientID: 你的clientID
#   clientSecret: 你的clientSecret
#   repo: 你的repo名
#   owner: 你的GitHub名
#   admin: [] 至少填写你的GitHub名
# leancloud: 要使用哪个请复制到根目录配置文件！
#   app_id: 你的appId
#   app_key: 你的appKey


############################### 杂项，请勿删除 ###############################
#valine配置
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  volantis: true # 是否启用volantis版本（禁止匿名，增加若干贴吧、QQ表情）
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  #   app_id: 你的appId
  #   app_key: 你的appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: true # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  lang: zh-cn
  highlight: true

# 搜索配置
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less渲染
less:
  compress: true
